name: Build Binary and Upload Release Artifact
on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetches all history for all tags and branches

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* # Ensure all tags are fetched

      - name: Set up Go 1.19
        uses: actions/setup-go@v5
        with:
          go-version: 1.19

      - name: Build and Upload Release
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCH: amd64 # or dynamically set based on your needs
        run: make release

