name: Upload containers to Docker Hub
on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  containers:
    name: Build container images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
#        - arm64
        - amd64
#        - ppc64le
#        - s390x

    steps:
      - name: Install dependencies required for multi-arch builds
        run: sudo apt-get update && sudo apt-get install qemu-user-static podman fuse-overlayfs

      - name: Set up Go 1.19
        uses: actions/setup-go@v5
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Login to Docker Hub
        run: podman login docker.io -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build kube-burner binary
        run: make build
        env:
          ARCH: ${{ matrix.arch }}

      - name: Build container image
        run: make images
        env:
          ARCH: ${{ matrix.arch }}
          ORG: ${ORG}

      - name: Push container image
        run: make push
        env:
          ARCH: ${{ matrix.arch }}
          ORG: ${ORG}

  manifest:
    name: Build container manifest
    runs-on: ubuntu-latest
    needs: containers
    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Login to Docker Hub
        run: podman login docker.io -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push manifest
        run: make manifest
        env:
          ORG: ${ORG}
